export const TYPES = {
  GET_IMAGES: "GET_IMAGES",
  GET_IMAGES_FILTER: "GET_IMAGES_FILTER",
  SET_CURRENT_FILTER: "SET_CURRENT_FILTER",
  SET_IMAGES_DATA: "SET_IMAGES_DATA",
  SET_CURRENT_PAGE: "SET_CURRENT_PAGE",
};
